name: 🧮 Calculator CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # ✅ Get GitHub username automatically
      - name: 📝 Set user name from GitHub actor
        run: echo "USER_NAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: 🧪 Run Tests
        run: mvn -B test

      - name: 📦 Build and Rename JAR
        run: |
          mvn clean package -DskipTests
          mv target/calculator.jar target/${{ env.USER_NAME }}-calculator.jar

      - name: 📤 Upload Personalized JAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.USER_NAME }}-calculator-jar
          path: target/${{ env.USER_NAME }}-calculator.jar

      - name: ✅ Summary
        run: |
          echo "## 🧮 CI/CD Summary" >> $GITHUB_STEP_SUMMARY
          echo "- GitHub User: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- JAR Uploaded: ${{ env.USER_NAME }}-calculator.jar" >> $GITHUB_STEP_SUMMARY